### ISSUE TITLE
Header : Cannot display all the social media set on the backend.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#2]
![2](https://cloud.githubusercontent.com/assets/18256652/15638542/264cde42-2654-11e6-96d8-3e6e707e16da.png)

**Comment by bukssaayman** [comment]
Fixed. Added youtube.

**Comment by iteano** [comment]
Not fixed. Please include the contact us section. 

![Uploading 2a.png…]()

**Comment by bukssaayman** [comment]
Done. added to contact section
